apiVersion: v1
kind: Pod
metadata:
  name: copypod
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ['sleep', 'infinity']
    volumeMounts:
    - name: pvc
      mountPath: /data
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: plex-database