---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: esphome
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`esphome.blakeshome.com`)
    kind: Rule
    services:
      - name: esphome
        port: 6052
    middlewares:
      - name: traefik-forward-auth
  tls:
    certResolver: le
---
apiVersion: v1
kind: Service
metadata:
  name: esphome
spec:
  selector:
    app.kubernetes.io/name: esphome
  ports:
    - protocol: TCP
      port: 6052
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esphome
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: esphome
  template:
    metadata:
      labels:
        app.kubernetes.io/name: esphome
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: esphome
          image: "esphome/esphome:1.14.3"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 6052
              protocol: TCP
          env:
            - name: TZ
              value: "America/Chicago"
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: esphome