---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: frigate
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`frigate.blakeshome.com`)
    kind: Rule
    services:
      - name: default-frigate
        port: 5000
    middlewares:
      - name: traefik-forward-auth
  tls:
    certResolver: le
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: frigate
  namespace: default
spec:
  chart:
      git: https://github.com/blakeblackshear/billimek-charts
      ref: master
      path: charts/frigate
  values:
    replicaCount: 1

    strategyType: Recreate

    image:
      repository: blakeblackshear/frigate
      tag: 0.6.0-rc1

    extraSecretForEnvFrom:
      - frigate-rtsp

    timezone: America/Chicago

    coral:
      enabled: true
      hostPath: /dev/bus/usb

    clips:
      enabled: true
      existingClaim: nvr-clips

    shmSize: 500Mi

    config: |
      web_port: 5000

      mqtt:
        host: default-mosquitto
        topic_prefix: frigate
        client_id: frigate

      ffmpeg:
        hwaccel_args:
          - -hwaccel
          - vaapi
          - -hwaccel_device
          - /dev/dri/renderD128
          - -hwaccel_output_format
          - yuv420p

      objects:
        track:
          - person

      cameras:
        back:
          ffmpeg:
            input: rtsp://viewer:{FRIGATE_BACK_PASSWORD}@10.0.10.10:554/cam/realmonitor?channel=1&subtype=2
          width: 1920
          height: 1080
          save_clips:
            enabled: True
          snapshots:
            draw_zones: true
          objects:
            filters:
              person:
                min_area: 2000
                threshold: 0.8
        front_door:
          ffmpeg:
            input: rtsp://viewer:{FRIGATE_BACK_PASSWORD}@10.0.10.118:554/cam/realmonitor?channel=1&subtype=2
          height: 1920
          width: 1080
          save_clips:
            enabled: True
          snapshots:
            draw_zones: true
          objects:
            filters:
              person:
                min_area: 20000
                threshold: 0.8
      
      zones:
        yard:
          back:
            coordinates:
              - 545,1077
              - 747,939
              - 788,805
              - 832,687
              - 893,573
              - 908,544
              - 1383,495
              - 1534,473
              - 1583,470
              - 1663,492
              - 1648,710
              - 1616,771
              - 1599,885
              - 1607,936
              - 1822,1078
            filters:
              person:
                min_area: 5000
                max_area: 100000
                threshold: 0.85
        driveway:
          back:
            coordinates: 1,1077,3,699,66,699,88,693,307,693,317,709,356,699,390,670,424,653,500,641,588,649,700,631,729,676,771,704,798,739,720,917,508,1046,369,1073
        front_porch:
          front_door:
            coordinates: 1,1065,312,1059,647,927,708,847,748,843,1001,863,1005,960,1033,1169,1078,1174,1080,1251,1079,1918,2,1919
            filters:
              person:
                min_area: 50000
                threshold: 0.85

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false

    service:
      port: 5000

    ingress:
      enabled: false