---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`jellyfin.blakeshome.com`)
    kind: Rule
    services:
      - name: jellyfin
        port: 8096
  tls:
    certResolver: le
---
kind: Service
apiVersion: v1
metadata:
  name: jellyfin
spec:
  type: ClusterIP
  ports:
  - port: 8096
    targetPort: 8096
---
kind: Endpoints
apiVersion: v1
metadata:
  name: jellyfin
subsets:
  - addresses:
      - ip: 192.168.2.237
    ports:
      - port: 8096