---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: radarr
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`radarr.blakeshome.com`)
    kind: Rule
    services:
      - name: radarr
        port: 7878
    middlewares:
      - name: traefik-forward-auth
  tls:
    certResolver: le
---
kind: Service
apiVersion: v1
metadata:
  name: radarr
spec:
  type: ClusterIP
  ports:
  - port: 7878
    targetPort: 7878
---
kind: Endpoints
apiVersion: v1
metadata:
  name: radarr
subsets:
  - addresses:
      - ip: 192.168.2.237
    ports:
      - port: 7878