---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`sonarr.blakeshome.com`)
    kind: Rule
    services:
      - name: sonarr
        port: 8989
    middlewares:
      - name: traefik-forward-auth
  tls:
    certResolver: le
---
kind: Service
apiVersion: v1
metadata:
  name: sonarr
spec:
  type: ClusterIP
  ports:
  - port: 8989
    targetPort: 8989
---
kind: Endpoints
apiVersion: v1
metadata:
  name: sonarr
subsets:
  - addresses:
      - ip: 192.168.2.237
    ports:
      - port: 8989