---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: esphome-restic-backups
spec:
  concurrencyPolicy: Forbid
  schedule: "40 8 * * *"
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          hostname: esphome
          volumes:
            - name: esphome
              persistentVolumeClaim:
                claimName: esphome
          containers:
          - name: backup
            image: restic/restic
            command:
            - "/bin/sh"
            - "-ec"
            - |
              find /data -maxdepth 1 -type f -name "*.yaml" > /tmp/backup-files
              restic --repo s3:s3.amazonaws.com/blakeshome-restic-backups --verbose --verbose backup --files-from /tmp/backup-files
            volumeMounts:
            - mountPath: "/data"
              name: esphome
            envFrom:
            - secretRef:
                name: restic-secrets
            env:
            - name: AWS_DEFAULT_REGION
              value: us-east-2
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: homeassistant-restic-backups
spec:
  concurrencyPolicy: Forbid
  schedule: "20 8 * * *"
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          hostname: homeassistant
          volumes:
            - name: homeassistant
              persistentVolumeClaim:
                claimName: homeassistant
          containers:
          - name: backup
            image: restic/restic
            args:
            - "--repo"
            - "s3:s3.amazonaws.com/blakeshome-restic-backups"
            - "--verbose"
            - "backup"
            - "/data"
            volumeMounts:
            - mountPath: "/data"
              name: homeassistant
            envFrom:
            - secretRef:
                name: restic-secrets
            env:
            - name: AWS_DEFAULT_REGION
              value: us-east-2
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: minecraft-restic-backups
spec:
  concurrencyPolicy: Forbid
  schedule: "0 8 * * *"
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          hostname: minecraft
          volumes:
            - name: minecraft
              persistentVolumeClaim:
                claimName: data-minecraft-creative-0
          containers:
          - name: backup
            image: restic/restic
            args:
            - "--repo"
            - "s3:s3.amazonaws.com/blakeshome-restic-backups"
            - "--verbose"
            - "--verbose"
            - '--exclude="bedrock_server-*"'
            - "backup"
            - "/data"
            volumeMounts:
            - mountPath: "/data"
              name: minecraft
            envFrom:
            - secretRef:
                name: restic-secrets
            env:
            - name: AWS_DEFAULT_REGION
              value: us-east-2
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: plex-restic-backups
spec:
  concurrencyPolicy: Forbid
  schedule: "10 8 * * *"
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          hostname: plex
          volumes:
            - name: plex-database
              persistentVolumeClaim:
                claimName: plex-database
          containers:
          - name: backup
            image: restic/restic
            args:
            - "--repo"
            - "s3:s3.amazonaws.com/blakeshome-restic-backups"
            - "--verbose"
            - "--verbose"
            - "backup"
            - "/data"
            volumeMounts:
            - mountPath: "/data"
              name: plex-database
            envFrom:
            - secretRef:
                name: restic-secrets
            env:
            - name: AWS_DEFAULT_REGION
              value: us-east-2
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: qbittorrent-restic-backups
spec:
  concurrencyPolicy: Forbid
  schedule: "30 8 * * *"
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          hostname: qbittorrent
          volumes:
            - name: qbittorrent
              persistentVolumeClaim:
                claimName: qbittorrent
          containers:
          - name: backup
            image: restic/restic
            args:
            - "--repo"
            - "s3:s3.amazonaws.com/blakeshome-restic-backups"
            - "--verbose"
            - "--verbose"
            - "backup"
            - "/data"
            volumeMounts:
            - mountPath: "/data"
              name: qbittorrent
            envFrom:
            - secretRef:
                name: restic-secrets
            env:
            - name: AWS_DEFAULT_REGION
              value: us-east-2
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: unifi-restic-backups
spec:
  concurrencyPolicy: Forbid
  schedule: "0 12 * * *"
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          hostname: unifi
          volumes:
            - name: unifi
              persistentVolumeClaim:
                claimName: unifi
          containers:
          - name: backup
            image: restic/restic
            args:
            - "--repo"
            - "s3:s3.amazonaws.com/blakeshome-restic-backups"
            - "--verbose"
            - "--verbose"
            - "backup"
            - "/data"
            volumeMounts:
            - mountPath: "/data"
              name: unifi
              subPath: "data/backup/autobackup"
            envFrom:
            - secretRef:
                name: restic-secrets
            env:
            - name: AWS_DEFAULT_REGION
              value: us-east-2
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: restic-backup-cleanup
spec:
  concurrencyPolicy: Forbid
  schedule: "13 11 * * *"
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          hostname: restic
          containers:
          - name: backup
            image: restic/restic
            args:
            - "--repo"
            - "s3:s3.amazonaws.com/blakeshome-restic-backups"
            - "--verbose"
            - "forget"
            - "--prune"
            - "--keep-last"
            - "5"
            envFrom:
            - secretRef:
                name: restic-secrets
            env:
            - name: AWS_DEFAULT_REGION
              value: us-east-2
          restartPolicy: OnFailure
