---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: longhorn-cors
  namespace: default
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "PUT"
      - "POST"
    accessControlAllowOriginList:
      - "https://longhorn.blakeshome.com"
    accessControlMaxAge: 100
    accessControlAllowHeaders:
      - "Content-Type"
    addVaryHeader: true
    customRequestHeaders:
      X-Forwarded-Proto: "https"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`longhorn.blakeshome.com`)
    kind: Rule
    services:
      - name: longhorn-frontend
        port: 80
    middlewares:
      - name: traefik-forward-auth
        namespace: default
      - name: longhorn-cors
        namespace: default
  tls:
    certResolver: le
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    git: https://github.com/longhorn/longhorn
    ref: v0.8.1
    path: chart
  values:
    defaultSettings:
      backupTarget: s3://blakeshome-longhorn-backuptarget@us-east-2/
      backupTargetCredentialSecret: aws-secret
      defaultReplicaCount: 1